// <auto-generated />
namespace TheSolutionBrothers.NFe.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ProjetoBase : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProjetoBase));
        
        string IMigrationMetadata.Id
        {
            get { return "201810012048409_ProjetoBase"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
